"""initial_schema

Revision ID: 7c0113735733
Revises: 
Create Date: 2026-05-06 13:07:37.786747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0113735733'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.Enum('most_360', 'most_2_0', name='formtype'), server_default='most_360', nullable=False))
        batch_op.add_column(sa.Column('opciones', sa.JSON(), nullable=True))
        batch_op.drop_constraint('preguntas_numero_key', type_='unique')

    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.alter_column('puntaje',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('self_respuestas', schema=None) as batch_op:
        batch_op.alter_column('puntaje',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.Enum('most_360', 'most_2_0', name='formtype'), server_default='most_360', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('form_type')

    with op.batch_alter_table('self_respuestas', schema=None) as batch_op:
        batch_op.alter_column('puntaje',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.alter_column('puntaje',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.create_unique_constraint('preguntas_numero_key', ['numero'])
        batch_op.drop_column('opciones')
        batch_op.drop_column('form_type')

    # ### end Alembic commands ###
