"""add_unique_constraints_answers

Revision ID: b0e5b68fde1e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-06 13:42:49.764424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e5b68fde1e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_respuesta_evaluador_pregunta', ['evaluador_id', 'pregunta_id'])

    with op.batch_alter_table('self_respuestas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_self_respuesta_subject_pregunta', ['subject_id', 'pregunta_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_respuestas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_self_respuesta_subject_pregunta', type_='unique')

    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_respuesta_evaluador_pregunta', type_='unique')

    # ### end Alembic commands ###
